DJobCentral/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    path('users/', include('users.urls')),
    path('jobs/', include('jobs.urls')),
    path('companies/', include('companies.urls')),
    path('search/<str:category>/', views.searchSpecificResults.as_view(), name = 'search-specific'),
    path('search/', views.searchResults.as_view(), name = 'search'),
    path('', views.homepage.as_view(), name = 'homepage'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index.as_view(), name = 'job-index'), 
    path('create', views.createJob.as_view(), name = 'create-job'),
    path('create/company_reload', views.companyUpdate.as_view(), name = 'company-update'),
    path('detail/<str:id>', views.jobDetail.as_view(), name = 'job-detail'),
    path('detail/<str:id>/apply', views.jobApply.as_view(), name = 'job-apply'),
    path('<str:field>', views.listJobs.as_view(), name = 'job-list'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserIndex.as_view(), name = 'user-index'),
    path('register', views.CustomRegistrationView.as_view(), name = 'register'),
    path('profiles/<str:id>', views.UserProfileView.as_view(), name = 'profile'),
    path('applications', views.AppliedJobsView.as_view(), name = 'applications'),
    path('applications/delete', views.DeleteApplication.as_view(), name = 'delete_application'),
    path('edit-profile', views.EditProfileView.as_view(), name = 'edit-profile'),
    path('recruitment', views.RecruiterView.as_view(), name = 'recruitment'),
    path('delete-applicant', views.deleteApplicant.as_view(), name = 'delete_applicant'),
    path('delete-job', views.deleteJob.as_view(), name = 'delete_job'),
    path('', include('django.contrib.auth.urls'))
]

users/models.py
from enum import unique
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import EmailField, ImageField
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
# Create your models here.
class CustomUser(AbstractUser):
    email = models.EmailField(unique = True)
    display_picture = models.ImageField(null = True, blank = True)
    about = models.TextField(null = True, blank = True)
    age = models.IntegerField(validators=[MinValueValidator(15), MaxValueValidator(110)], null = True, blank = True)
    experience_in_years = models.IntegerField(validators=[MaxValueValidator(60)], null = True, blank = True)
    phone = models.CharField(max_length=10, validators=[RegexValidator('[0-9]{10}')], null = True, blank = True)

users/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        )

    def save(self, commit = True):
        user = super(CustomUserCreationForm, self).save(commit = False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

class CustomUserChangeForm(UserChangeForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

    def save(self, commit = True):
        user = super(CustomUserChangeForm, self).save(commit = False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user

class UserEditForm(ModelForm):
    class Meta:
        model = get_user_model()
        fields = [
            'first_name',
            'last_name',
            'email',
            'age',
            'experience_in_years',
            'phone'
            ]

users/views.py
from http.client import HTTPResponse
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView
from django.views import View
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, UserEditForm
from .models import CustomUser
from jobs.models import Job
# Create your views here.

class CustomRegistrationView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

class UserIndex(View):
    def get(self, request):
        return render(request, 'users/index.html', {
        })

class UserProfileView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        visiting_profile = get_object_or_404(CustomUser, username = kwargs['id'])
        
        return render(request, 'users/profile-detail.html', {
            'profile' : visiting_profile
        } )

class EditProfileView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('users:login'))
        form = UserEditForm(instance=request.user)
        return render(request, 'users/edit-profile.html', {
            'form' : form
        })
    def post(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('users:login'))
        form = UserEditForm(request.POST, instance=request.user)
        if not form.is_valid():
            return render(request, 'users/edit-profile.html', {
            'form' : form
            })
        form.save()
        return HttpResponseRedirect(reverse_lazy('users:profile', args=[request.user.username]))

class AppliedJobsView(View):
    def get(self, request):
        return render(request, 'users/jobs-applied.html')

class DeleteApplication(View):
    def post(self, request):
        if not request.user.is_authenticated:
            raise Http404
        request.user.jobs_applied.remove(Job.objects.get(pk=request.POST['job_id']))
        return render(request, 'users/jobs-applied-htmx.html')

class RecruiterView(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('users:login'))
        return render(request, 'users/jobs-hiring.html')

class deleteApplicant(View):
    def post(self, request):
        job = Job.objects.get(pk = request.POST['job_id'])
        users = get_user_model()
        job.applicants.remove(users.objects.get(username = request.POST['applicant']))
        return render(request, 'users/delete-applicant.html', {
            'job': job
        })

class deleteJob(View):
    def post(self, request):
        Job.objects.get(pk = request.POST['job_id']).delete()
        return render(request, 'users/blank.html')

        

users/templates/users/delete-applicant.html
<li class = "res">
    <a class = "res-main" href = "{% url 'jobs:job-detail' job.id %}">{{job}}</a>
    <form hx-post = "{% url 'users:delete_job' %}" hx-target = "#job{{job.id}}">
        <input hidden name = "job_id" value = "{{job.id}}">
        <button type = "submit" class = "delete-btn" id = "{{job.id}}">Delete Job</button>
    </form>
    <br>Applicants :
        <ul>
            {% for applicant in job.applicants.all %}
            <li class = "option"> <a href = "{% url 'users:profile' applicant.username %}">{{applicant.username}}</a>
                    <form hx-post = "{% url 'users:delete_applicant' %}" hx-target = "#job{{job.id}}" hx-swap = "outerHTML">
                        {% csrf_token %}
                        <input hidden name = "job_id" value = "{{job.id}}">
                        <input hidden name = "applicant" value = {{applicant.username}}>
                        <button type = "submit" class = "delete-btn" id = "{{job.id}}">Delete Application</button>
                    </form>
                </li>
            {% endfor %}
        
        </ul>
</li>

users/templates/users/edit-profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Edit Profile</title>
{% endblock title %}

{% block content %}
<h2 class = "text-2xl">Edit Profile</h2>
<br><br>
<form method = "post">
{% csrf_token %}
{{form|crispy}}
<br>
<button type="submit" class = "submit-btn">Save Changes</button>
<br>
</form>
{% endblock content %}

users/templates/users/index.html
{% extends 'base.html' %}

{% block title %}
<title>User Home</title>
{% endblock title %}

{% block content %}
<h2 class = "text-3xl">User Home</h2>
<br>
<p>
    {% if user.is_authenticated %}Hello{% if user.first_name %} {{user.first_name}}{% endif %}, please proceed to the sections you wish to work with. 
    <br><br>
    <form class = "" action = "{% url 'users:applications' %}">
    <button class = "option px-6" type = "submit">My Applications</button>
    </form>
    <form class = "" action = "{% url 'users:recruitment' %}">
        <button class = "option px-6" type = "submit">Recruitment</button>
        </form>

    {% else %}Hello stranger. <a href = "{% url 'users:login' %}">Log In</a> to access the website's functionality.
    {% endif %}
</p>
{% endblock content %}

users/templates/users/jobs-applied-htmx.html
<h2 class = "text-2xl hover:font-extrabold">Job Applications</h2>
<p>You currently have {{user.jobs_applied.count}} active applications.</p>
<br><br>
<p>
<ul>
{% for job in user.jobs_applied.all %}
    <li class = "res">
        <a class = "res-main" href = "{% url 'jobs:job-detail' job.id %}">{{job.job_title|title}}</a>
        <ul><li class = "hover:font-semibold">Recruiter : <a href = "{% url 'users:profile' job.recruiter.username %}">{{job.recruiter}}</a></li>
        <li><form hx-post = "{% url 'users:delete_application' %}" hx-target = "#main">
            {% csrf_token %}
            <input hidden name = "job_id" value = "{{job.id}}">
            <button class = "delete-btn" type = "submit" id = "{{job.id}}">Delete Application</button>
        </form>
    </ul>
    </li>
    <br>
{% endfor %}
</ul>
</p>

users/templates/users/jobs-applied.html
{% extends 'base.html' %}

{% block title %}
<title>Job Applications</title>
{% endblock title %}

{% block content %}
<div id = "main">
<h2 class = "text-2xl hover:font-extrabold">Job Applications</h2>
<p>You currently have {{user.jobs_applied.count}} active applications.</p>
<br><br>
<p>
<ul>
{% for job in user.jobs_applied.all %}
    <li class = "res">
        <a class = "res-main" href = "{% url 'jobs:job-detail' job.id %}">{{job.job_title}}</a>
        <ul><li class = "hover:font-semibold">Recruiter : <a href = "{% url 'users:profile' job.recruiter.username %}">{{job.recruiter}}</a></li>
        <li><form hx-post = "{% url 'users:delete_application' %}" hx-target = "#main">
            {% csrf_token %}
            <input hidden name = "job_id" value = "{{job.id}}">
            <button class = "delete-btn" type = "submit" id = "{{job.id}}">Delete Application</button>
        </form>
    </ul>
    </li>
    <br>
{% endfor %}
</ul>
</p>
</div>
{% endblock content %}

users/templates/users/jobs-hiring.html
{% extends 'base.html' %}

{% block title %}
<title>Job Applications</title>
{% endblock title %}

{% block content %}
<div id = "main">
<div class = "grid grid-cols-3">
<div class = "col-span-2"> 
<h2 class = "text-3xl">Recruitment</h2>
<br>
<p>You currently have {{user.jobs_hiring.count}} active jobs.</p>
</div>
<div class = "grid place-content-center">
<a class = "create-btn" href = "{% url 'jobs:create-job' %}">+ Create Job</a>
</div>
</div>
<br><br>
<p>
<ul>
{% for job in user.jobs_hiring.all %}
<div id = "job{{job.id}}">
    <li class = "res">
        <a class = "res-main" href = "{% url 'jobs:job-detail' job.id %}">{{job}}</a>
        <form hx-post = "{% url 'users:delete_job' %}" hx-target = "#job{{job.id}}">
            <input hidden name = "job_id" value = "{{job.id}}">
            <button type = "submit" class = "delete-btn" id = "{{job.id}}">Delete Job</button>
        </form>
        <br>Applicants :
            <ul>
                {% for applicant in job.applicants.all %}
                <li class = "option"> <a href = "{% url 'users:profile' applicant.username %}">{{applicant.username}}</a>
                        <form hx-post = "{% url 'users:delete_applicant' %}" hx-target = "#job{{job.id}}" hx-swap = "outerHTML">
                            {% csrf_token %}
                            <input hidden name = "job_id" value = "{{job.id}}">
                            <input hidden name = "applicant" value = {{applicant.username}}>
                            <button type = "submit" class = "delete-btn" id = "{{job.id}}">Delete Application</button>
                        </form>
                    </li>
                {% endfor %}
            
            </ul>
    </li>
</div>
    <br><br>
{% endfor %}
</ul>
</p>
</div>
{% endblock content %}

users/templates/users/profile-detail.html
{% extends 'base.html' %}

{% block title %}
<title>DJC|{{profile.username}}</title>
{% endblock title %}

{% block content %}
<div class = "m-8">
<br>
<h1>{% if profile.display_picture %}<img src = "{{profile.display_picture.url}}" style = "height:120px; width:160px" alt = "{{profile.username}}'s dp">{% endif %}
</h1>
<h2 class = "text-2xl">{{profile.username}}</h2>
<h1 class = "text-3xl">{{profile.get_full_name|title}}</h1>
<br><br>

<p>
{% if profile.email %}Email : {{profile.email}}{% endif %}<br>
{% if profile.about %}About : {{profile.about}}<br>{% endif %}
{% if profile.age %}Age : {{profile.age}}<br>{% endif %}
{% if profile.experience_in_years %}Experience : {{profile.experience_in_years}} Years<br>{% endif %}
{% if profile.phone %}Phone : {{profile.phone}}<br>{% endif %}
</p>
<br><br>
<div class = "m-0 p-0 h-36">
{% if user == profile %}
<a class = "option m-0 mt-10" href = "{% url 'users:edit-profile' %}">Edit Profile</a><span>&nbsp;&nbsp;&nbsp;</span>
<a class = "option m-0 mt-16" href = "{% url 'users:logout' %}">Logout</a> 
{% endif %}
</div>
</div>
{% endblock content %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}

{% block title %}
<title>Register|DJC</title>
{% endblock title %}

{% block content %}
<h2>Register</h2>
<br>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <br>
  <button type="submit" class = "bg-blue-300 hover:bg-blue-500 shadow-lg hover:shadow-blue-500/50 text-stone-700 px-6 py-2 rounded-lg">Register</button>
</form>
<br>
{% endblock content %}