DJobCentral/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    path('users/', include('users.urls')),
    path('jobs/', include('jobs.urls')),
    path('companies/', include('companies.urls')),
    path('search/<str:category>/', views.searchSpecificResults.as_view(), name = 'search-specific'),
    path('search/', views.searchResults.as_view(), name = 'search'),
    path('', views.homepage.as_view(), name = 'homepage'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index.as_view(), name = 'job-index'), 
    path('create', views.createJob.as_view(), name = 'create-job'),
    path('create/company_reload', views.companyUpdate.as_view(), name = 'company-update'),
    path('detail/<str:id>', views.jobDetail.as_view(), name = 'job-detail'),
    path('detail/<str:id>/apply', views.jobApply.as_view(), name = 'job-apply'),
    path('<str:field>', views.listJobs.as_view(), name = 'job-list'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserIndex.as_view(), name = 'user-index'),
    path('register', views.CustomRegistrationView.as_view(), name = 'register'),
    path('profiles/<str:id>', views.UserProfileView.as_view(), name = 'profile'),
    path('applications', views.AppliedJobsView.as_view(), name = 'applications'),
    path('applications/delete', views.DeleteApplication.as_view(), name = 'delete_application'),
    path('edit-profile', views.EditProfileView.as_view(), name = 'edit-profile'),
    path('recruitment', views.RecruiterView.as_view(), name = 'recruitment'),
    path('delete-applicant', views.deleteApplicant.as_view(), name = 'delete_applicant'),
    path('delete-job', views.deleteJob.as_view(), name = 'delete_job'),
    path('', include('django.contrib.auth.urls'))
]

templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}
        <title>The Job Portal</title>
    {% endblock title %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <script src="https://unpkg.com/htmx.org@1.7.0" integrity="sha384-EzBXYPt0/T6gxNp0nuPtLkmRpmDBbjg6WmCUZRLXBBwYYmwAUxzlSGej0ARHX0Bo" crossorigin="anonymous"></script>
</head>

<body class = " grid grid-cols-6 static w-full bg-slate-700 font-mono text-xl font-semibold leading-relaxed tracking-[.15em] h-screen mr-4">
    <div class = "block grow-0 max-w-[18%] text-3xl h-screen sticky z-0">
        {% include "nav.html" %}
    </div>

    <div class = "flex flex-col col-span-5 h-screen mt-6 ml-10 grow-0 pb-6">
        <div class = "sticky">
        {% include "search_bar.html" %}
        </div>
        <div class = "block overflow-y-auto text-stone-700 rounded-xl grow bg-yellow-200 m-2 p-6">
            {% block content %}
                <p class = "ml-5">
                    Default Content. <br>
                    If you're seeing then this page is yet to be modified.
                </p>
            {% endblock content %}
    
        </div>
    
    <footer style="h-30 w-full"></footer>
    </div>
    <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
    </script>   
</body>
</html>

templates/homepage.html
{% extends 'base.html' %}

{% block title %}
<title>home</title>
{% endblock title %}

{% block content %}
<div class = "p-6 text-3xl">Welcome to DJOBCONNECT</div>
<br>
<p>The portal offers users an interface to connect with recruiters and potential new hires. </p>
<p>Users can apply for available jobs or hire people with a single account.</p>
<br>
{% if user.is_authenticated %}
<p>Check out Jobs link for exploring the available jobs, or create one yourself. Manage all applications in the Users section. Make sure to update your profile, you can access your profile by clicking on the bottom-left link.</p>
{% else %}
<p> Login/Register to access all functionality of the portal.</p> 
{% endif %}
{% endblock content %}

templates/loads.html
{% load static %}
{% load tailwind_tags %}

templates/nav.html
<nav class = "flex flex-col text-yellow-100 justify-around max-w-[19%] h-screen fixed">
    <a href="{% url 'homepage' %}"><div class = "text-center flex bg-yellow-200 shadow-lg shadow-stone-700/50 hover:bg-blue-300 hover:shadow-lg hover:shadow-blue-300/30 transition rounded-2xl text-stone-700 m-8 text-3xl p-4 h-24 mr-2 justify-center place-items-center">DJOBCONNECT</div></a>
    <a href="{% url 'homepage' %}"><div class = "text-center p-10 ml-5 hover:border-t-2 hover:border-b-2 hover:border-yellow-300 hover:text-yellow-300">HOME</div></a>
    <a href="{% url 'jobs:job-index' %}"><div class = "text-center p-10 ml-5 hover:border-t-2 hover:border-b-2 hover:border-yellow-300 hover:text-yellow-300">JOBS</div></a>
    <a href="{% url 'users:user-index' %}"><div class = "text-center p-10 ml-5 hover:border-t-2 hover:border-b-2 hover:border-yellow-300 hover:text-yellow-300">USERS</div></a>
    {% if user.is_authenticated %}
    <a href="{% url 'users:profile' user.username %}"><div class = "text-center text-xl rounded-2xl bg-slate-700 shadow-lg shadow-blue-500/50 hover:shadow-blue-500/30 hover:-translate-y-0.5 hover:bg-stone-800 hover:text-blue-500 transform transition text-blue-500 m-5 p-2 pt-6 pb-6 mb-4 justify-center place-items-center truncate">{{user.username}}</div></a>
    {% else %}
    <div class = "flex flex-col text-center p-10 ">
        <a href="{% url 'users:login'%}"><div class = "mt-4 text-blue-300 ml-5 hover:border-t-2 hover:border-b-2 hover:border-blue-500 hover:text-blue-500"> LOGIN </div></a>
        <div> </div>
        <a href="{% url 'users:register'%}"><div class = "mt-4 text-blue-300 ml-5 hover:border-t-2 hover:border-b-2 hover:border-blue-500 hover:text-blue-500">REGISTER</div></a>
    {% endif %}
</nav>

templates/search-results.html
{% extends 'base.html' %}

{% block content %}
Search results for "{{query}}"
<br>

<div id="tabs" hx-get = "{% url 'search-specific' 'all' %}?search={{query}}" hx-trigger="load after:100ms" hx-target="#tab-content" hx-swap="innerHTML">

<form class="tab-list">
    Search for : 
    <button hx-get= "{% url 'search-specific' 'jobs' %}?search={{query}}" class="text-blue-400 hover:text-red-400" type = "submit">Jobs</button>
    <button hx-get= "{% url 'search-specific' 'users' %}?search={{query}}" type = "submit" class = "text-blue-400 hover:text-red-400">Users</button>
    <button hx-get= "{% url 'search-specific' 'companies' %}?search={{query}}" type = "submit" class = "text-blue-400 hover:text-red-400">Companies</button>
    <button hx-get= "{% url 'search-specific' 'all' %}?search={{query}}" class="text-blue-400 hover:text-red-400" type = "submit">All</button>
</form>

<div class="tab-content" id="tab-content">

</div>
</div>
{% endblock content %}

templates/search-spec-results.html
<ul>
    <p>The query "{{query}}" fetched {{count}} 
        {% if category == 'all' %}results.
        {% elif category == 'jobs' %}jobs.
        {% elif category == 'users' %}users.
        {% elif category == 'companies' %}companies.
        {% endif %}</p>
{% if category == 'all' %}
	{% for result in results.jobs %}
        <a href = "{% url 'jobs:job-detail' result.id %}">
            <li class = "res">
            <p class = "res-pretext">
                Job
            </p>
            <p class = "res-main">
                {{result.job_title|title}}
            </p>
            <p class = "res-post">
                {{result.company|title}}
            </p>
        </li>
        </a>
    {% endfor %}
    {% for result in results.users %}
        <a href = "{% url 'users:profile' result.username %}">
            <li class = "res">
            <p class = "res-pretext">
                User
            </p>
            <p class = "res-main">
                {{result.username}}
            </p>
            <p class = "res-post">
                {{result.get_full_name|title}}
            </p>
        </li>
        </a>
    {% endfor %}
    {% for result in results.companies %}
        <li class = "res">
        <p class = "res-pretext">
            Company
        </p>
        <p class = "res-main">
            {{result.name|title}}
        </p>
    {% endfor %}

    {% elif category == 'jobs' %}
    {% for result in results %}
        <a href = "{% url 'jobs:job-detail' result.id %}">
            <li class = "res">
            <p class = "res-pretext">
                Job
            </p>
            <p class = "res-main">
                {{result.job_title|title}}
            </p>
            <p class = "res-post">
                {{result.company|title}}
            </p>
        </li>
        </a>
    {% endfor %}

{% elif category == 'users'%}
    {% for result in results %}
        <a href = "{% url 'users:profile' result.username %}">
            <li class = "res">
            <p class = "res-pretext">
                User
            </p>
            <p class = "res-main">
                {{result.username}}
            </p>
            <p class = "res-post">
                {{result.get_full_name|title}}
            </p>
        </li>
        </a>
        {% endfor %}
{% elif category == 'companies'%}
    {% for result in results %}
        <li class = "res">
            <p class = "res-pretext">
                Company
            </p>
            <p class = "res-main">
                {{result.name|title}}
            </p>
        {% endfor %}
{% endif %}
</ul>

templates/search_bar.html
<div class="flex flex-1 justify-center align-items-center px-2 mb-10">
    <form class="flex border-0 relative w-3/4 justify-center focus:outline-none text-blue-300" method = "get" action = "{% url 'search' %}">
        <input aria-label="search" type="search" name="search" placeholder="Search" class="peer w-full bg-slate-700 border-0 border-b-2 border-b-blue-300 focus:border-b-blue-500 focus:text-blue-500 placeholder-blue-300 focus:placeholder-blue-500 justify-center place-items-center transition rounded py-3 px-3 pl-14 appearance-none outline-none leading-normal">
        <div class="absolute search-icon peer-focus:text-blue-500" style="top: 1rem; left: .8rem;">
            <svg class="fill-current pointer-events-none w-6 h-6" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
            </svg>
        </div>
    </form>
</div>