DJobCentral/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.views.generic import TemplateView


urlpatterns = [
    path('users/', include('users.urls')),
    path('jobs/', include('jobs.urls')),
    path('companies/', include('companies.urls')),
    path('search/<str:category>/', views.searchSpecificResults.as_view(), name = 'search-specific'),
    path('search/', views.searchResults.as_view(), name = 'search'),
    path('', views.homepage.as_view(), name = 'homepage'),
    path("__reload__/", include("django_browser_reload.urls")),
    path('admin/', admin.site.urls),
]

companies/urls.py
from django.urls import path
from . import views

app_name = 'companies'

urlpatterns = [
    path('add', views.addCompanyView.as_view(), name = 'add-company')
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.index.as_view(), name = 'job-index'), 
    path('create', views.createJob.as_view(), name = 'create-job'),
    path('create/company_reload', views.companyUpdate.as_view(), name = 'company-update'),
    path('detail/<str:id>', views.jobDetail.as_view(), name = 'job-detail'),
    path('detail/<str:id>/apply', views.jobApply.as_view(), name = 'job-apply'),
    path('<str:field>', views.listJobs.as_view(), name = 'job-list'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserIndex.as_view(), name = 'user-index'),
    path('register', views.CustomRegistrationView.as_view(), name = 'register'),
    path('profiles/<str:id>', views.UserProfileView.as_view(), name = 'profile'),
    path('applications', views.AppliedJobsView.as_view(), name = 'applications'),
    path('applications/delete', views.DeleteApplication.as_view(), name = 'delete_application'),
    path('edit-profile', views.EditProfileView.as_view(), name = 'edit-profile'),
    path('recruitment', views.RecruiterView.as_view(), name = 'recruitment'),
    path('delete-applicant', views.deleteApplicant.as_view(), name = 'delete_applicant'),
    path('delete-job', views.deleteJob.as_view(), name = 'delete_job'),
    path('', include('django.contrib.auth.urls'))
]

jobs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from companies.models import Company

# Create your models here.
field_choices = (('IT', 'Information Technology'), ('SL', 'Sales'), ('MG', 'Management'), ('AC', 'Analytics/Consulting'), ('OT', 'Other'))
field_choices_dict = dict(field_choices)

class Job(models.Model):
    job_title = models.CharField(max_length = 64)
    field = models.CharField(max_length = 2, choices = field_choices)
    company = models.ForeignKey(Company, on_delete = models.CASCADE)
    description = models.TextField(null = True, blank = True)
    salary = models.IntegerField(null=True, blank = True)
    recruiter = models.ForeignKey(get_user_model(), on_delete = models.CASCADE, related_name = 'jobs_hiring')
    applicants = models.ManyToManyField(get_user_model(), related_name='jobs_applied', null=True, blank=True)

    def __str__(self):
        return f'{self.job_title} : {self.company.name}'

jobs/forms.py
from django import forms
from .models import Job

class JobCreationForm(forms.ModelForm):
    class Meta:
        model = Job
        exclude = ['recruiter', 'applicants']

jobs/views.py
from re import template
from django.shortcuts import render, get_object_or_404
from django.views import View
from .models import Job, field_choices, field_choices_dict
from django.urls import reverse, reverse_lazy
from django.http import Http404, HttpResponseRedirect
from .forms import JobCreationForm
# Create your views here.

class index(View):
    def get(self, request):
        return render(request, "jobs/index.html", {'field_choices' : field_choices})
    
class listJobs(View):
    
    def get(self, request, *args, **kwargs):
        
        if kwargs['field'] not in field_choices_dict.keys():
            raise Http404('<h1>404</h1> <br><br><h3>The page cannot be found.</h3>')

        filtered_jobs = Job.objects.filter(field = kwargs['field']) 

        return render(request, "jobs/category_wise_list.html", {
            'field_choices' : field_choices,
            'field_chosen' : field_choices_dict[kwargs['field']],
            'joblist' : filtered_jobs
        })

class jobDetail(View):
    def get(self, request, *args, **kwargs):
        job = get_object_or_404(Job, pk = kwargs['id'])
        user = request.user
        type_user = None
        if user == job.recruiter:
            type_user = 'recruiter'
        elif job.applicants.filter(pk = user.pk).exists():
            type_user = 'applicant'
        else:    
            type_user = 'neither'
        return render(request, 'jobs/job_detail.html', {
            'job' : job,
            'type_user' : type_user,
            'field_choices' : field_choices
        })
class jobApply(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        job = get_object_or_404(Job, pk = kwargs['id'])
        if user.is_authenticated:
            if user != job.recruiter:
                job.applicants.add(user)
            type_user = None
            if user == job.recruiter:
                type_user = 'recruiter'
            elif job.applicants.filter(pk = user.pk).exists():
                type_user = 'applicant'
            else:    
                type_user = 'neither'
            
            return render(request, "jobs/apply.html", {
                'type_user' : type_user
            })
        else: 
            raise Http404

        
class createJob(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('users:login'))
        form = JobCreationForm()
        return render(request, 'jobs/create_job.html', {
            'form' : form
        })
    def post(self, request):
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse('users:login'))
        form = JobCreationForm(request.POST)
        if not form.is_valid():
            return render(request, 'jobs/create_job.html', {
            'form' : form
            })
        new_job = form.save(commit = False)
        new_job.recruiter = request.user
        new_job.save()
        return HttpResponseRedirect(reverse_lazy('users:recruitment'))

class companyUpdate(View):
    def get(self, request):
        form = JobCreationForm()
        return render(request, 'jobs/company_update.html', {
            'form' : form
        })

jobs/templates/jobs/apply.html
{% if type_user == 'applicant' %}
<button class = "submit-btn bg-green-300 shadow-green-500/50 text-green-500" type = "submit">Applied</button> 
{% elif type_user == 'neither' %}
<button id = "apply" class = "submit-btn" hx-get = "{% url 'jobs:job-apply' job.id %}" hx-target= "#apply" hx-swap = "innerHTML" type = "submit">Apply</button>
{% else %}
<div class = "text-red-500">You cannot apply to your own jobs.</div>
{% endif %}

jobs/templates/jobs/category_wise_list.html
{% extends 'base.html' %}

{% block title %}
<title>{{field_chosen.1}} Jobs</title>
{% endblock title %}

{% block content%}
<h1 class = "text-2xl">{{field_chosen|title}} Jobs</h1>
<br><br>
<ul>
    {% for result in joblist %}
    <a href = "{% url 'jobs:job-detail' result.id %}">
        <li class = "res">
        <p class = "res-pretext">
            Job
        </p>
        <p class = "res-main">
            {{result.job_title|title}}
        </p>
        <p class = "res-post">
            {{result.company|title}}
        </p>
    </li>
    </a>
{% endfor %}
</ul>
<br><br>
<table>
</table>
{% endblock content%}

jobs/templates/jobs/company_update.html
{% load crispy_forms_tags %}

{{ form|crispy }}

jobs/templates/jobs/create_job.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
<title>Create New Job Posting</title>
{% endblock title %}

{% block content %}
<div class = "grid grid-cols-3">
<h2 class = "text-2xl col-span-2">New Job Posting</h2>
<div class = "flex justify-evenly items-center">
  <a class = "create-btn" href = "{% url 'companies:add-company' %}" target = "_blank" rel = "noopener noreferrer">+ Add Company</a>
  <button class = "option p-1 bg-red-400" hx-get = {% url 'jobs:company-update' %} hx-target = "#form" ><svg class = "mx-4" xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24"><path d="M20.944 12.979c-.489 4.509-4.306 8.021-8.944 8.021-2.698 0-5.112-1.194-6.763-3.075l1.245-1.633c1.283 1.645 3.276 2.708 5.518 2.708 3.526 0 6.444-2.624 6.923-6.021h-2.923l4-5.25 4 5.25h-3.056zm-15.864-1.979c.487-3.387 3.4-6 6.92-6 2.237 0 4.228 1.059 5.51 2.698l1.244-1.632c-1.65-1.876-4.061-3.066-6.754-3.066-4.632 0-8.443 3.501-8.941 8h-3.059l4 5.25 4-5.25h-2.92z"/></svg></button>
</div>
</div>
<form method="post" class = "">
  <br>
  {% csrf_token %}
  <div id = "form">

  {{ form|crispy }}
  </div>
  <br>
  <button type="submit" class = "submit-btn">Create</button>
</form>
{% endblock content %}

jobs/templates/jobs/index.html
{% extends 'base.html' %}

{% block title %}
<title>DJC | Jobs</title>
{% endblock title %}

{% block content %}
<div class = "grid grid-cols-3">
<div class = "col-span-2">
<h2 class = "text-3xl"> Jobs </h2>
<br>
<p> Please select the category, the one concerned with the kind of jobs you wish to explore </p>
</div>
<div class = "grid place-content-center">
<a class = "create-btn" href = "{% url 'jobs:create-job' %}">+ Create Job</a>
</div>
</div>

<br>
<ul>
{% for field in field_choices %}
    
    <a href = "{% url "jobs:job-list" field.0 %}"><li class = "option">{{field.1}}</li></a>
{% endfor %}

</ul>
{% endblock content %}

jobs/templates/jobs/job_detail.html
{% extends 'base.html' %}

{% block title %}
<title>DJC | {{job.job_title}}</title>

{% endblock title %}

{% block content%}
<h2 class = "text-3xl">{{job.job_title}}</h2>
{% if job.company.logo %}<img src="{{job.company.logo.url}}" style = "height:120px; width:160px" alt = "{{job.company.name}}">
{% endif %}
<br>
<h3>Company : {{job.company.name}}</h3>

<br><br>
    <p>
        {{job.description}}
    </p>
<br>
    {% if job.salary is not null%} 
    <p>Salary : {{ job.salary }}</p>
    {% endif %}
    <p> Recruiter : <a class = "text-blue-500 font-normal hover:font-semibold" href = "{% url 'users:profile' job.recruiter %}">{% if job.recruiter.get_full_name  %}{{ job.recruiter.get_full_name }}{% else %}{{job.recruiter.username}}{% endif %}</a></p>
<br>
{% if user.is_authenticated %}
<div id = "apply">
    {% if type_user == 'applicant' %}
    <button class = "submit-btn bg-green-300 shadow-green-500/50 text-green-500" type = "submit">Applied</button> 
    {% elif type_user == 'neither' %}
    <button class = "submit-btn" hx-get = "{% url 'jobs:job-apply' job.id %}" hx-target= "#apply" hx-swap = "innerHTML" type = "submit">Apply</button>
    {% else %}
    <div class = "font-light text-red-500">You cannot apply to your own jobs.</div>
    {% endif %}
</div>
{% else %}
<form action = {% url 'users:login' %}>
<button class = "submit-btn" type = "submit">Apply</button>
</form>
{% endif %}
<br><br>
{% endblock content%}